# Generated by Django 5.2.13 on 2026-07-24 13:03

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0227_alter_interface_speed_bigint'),
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
        ('netbox_it_landscape', '0003_application_auth_modes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(default='medical_device', max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('device_class', models.CharField(blank=True, max_length=5)),
                ('criticality', models.CharField(default='standard', max_length=30)),
                ('status', models.CharField(default='in_service', max_length=30)),
                ('care_unit', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('gmao_id', models.CharField(blank=True, max_length=50)),
                ('mercator_id', models.CharField(blank=True, max_length=200)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('ae_title', models.CharField(blank=True, max_length=100)),
                ('listen_ports', models.CharField(blank=True, max_length=200)),
                ('connection_mode', models.CharField(blank=True, max_length=30)),
                ('ssid', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('end_of_support', models.DateField(blank=True, null=True)),
                ('edr', models.CharField(blank=True, max_length=100)),
                ('edr_exclusions', models.CharField(blank=True, max_length=200)),
                ('vendor_account', models.CharField(blank=True, max_length=100)),
                ('vault_ref', models.CharField(blank=True, max_length=200)),
                ('remote_maintenance', models.BooleanField(blank=True, null=True)),
                ('remote_maintenance_mode', models.CharField(blank=True, max_length=100)),
                ('network_exposure', models.CharField(default='unknown', max_length=30)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('applications', models.ManyToManyField(blank=True, related_name='biomed_equipments', to='netbox_it_landscape.application')),
                ('dcim_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomed_equipment', to='dcim.device')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomed_equipments', to='dcim.location')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomed_equipments', to='dcim.manufacturer')),
                ('primary_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biomed_equipments', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomed_equipments', to='ipam.vlan')),
            ],
            options={
                'verbose_name': 'biomedical equipment',
                'verbose_name_plural': 'biomedical equipments',
                'ordering': ('site', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EquipmentFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('protocol', models.CharField(blank=True, max_length=50)),
                ('message_type', models.CharField(blank=True, max_length=100)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('encrypted', models.BooleanField(blank=True, null=True)),
                ('eai', models.CharField(blank=True, max_length=100)),
                ('source_endpoint', models.CharField(blank=True, max_length=200)),
                ('eai_endpoint', models.CharField(blank=True, max_length=200)),
                ('target_endpoint', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='production', max_length=30)),
                ('prtg_sensor', models.URLField(blank=True)),
                ('recovery_procedure', models.BooleanField(blank=True, null=True)),
                ('vendor_contact', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows_as_source', to='netbox_biomed.equipment')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows_as_target', to='netbox_biomed.equipment')),
            ],
            options={
                'verbose_name': 'equipment flow',
                'verbose_name_plural': 'equipment flows',
                'ordering': ('source', 'target', 'protocol'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Plateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('manager', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biomed_plateaux', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'technical platform',
                'verbose_name_plural': 'technical platforms',
                'ordering': ('site', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='equipment',
            name='plateau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='netbox_biomed.plateau'),
        ),
        migrations.AddConstraint(
            model_name='plateau',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='netbox_biomed_plateau_unique_site_name'),
        ),
    ]
